blank_issues_enabled: false
contact_links:
  - name: RCAC Help Desk (Open a Ticket)
    url: mailto:<rcac-help@purdue.edu>
    about: For technical user support issues or questions after reading the user-guides, please submit a ticket to rcac-help@purdue.edu so our RCAC Support can help you from there.
  - name: RCAC Homepage
    url: https://www.rcac.purdue.edu
  - name: RCAC Documentation
    url: https://rcac-docs-demo.readthedocs.io
    about: Check the official RCAC documentation first to see if your question is already answered.