authors:
  rcac:
    name: Rosen Center for Advanced Computing
    description: Rosen Center for Advanced Computing
    url: https://www.rcac.purdue.edu
    avatar: assets/purdue.png
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  jin456:
    name: Guangzhen Jin
    description: Senior Computational Scientist
    avatar: https://www.rcac.purdue.edu/files/users/jin456/photo.jpg
    slug: https://www.rcac.purdue.edu/about/staff/jin456
    url: https://www.rcac.purdue.edu/about/staff/jin456
  glentner:
    name: Geoffrey Lentner
    description: Lead Research Data Scientist
    avatar: https://www.rcac.purdue.edu/files/users/glentner/photo.jpeg
    slug: https://www.rcac.purdue.edu/about/staff/glentner
    url: https://www.rcac.purdue.edu/about/staff/glentner
  rderue:
    name: Ryan DeRue
    description: Senior Computational Scientist
    avatar: https://www.rcac.purdue.edu/files/users/rderue/photo.jpg
    slug: https://www.rcac.purdue.edu/about/staff/rderue
    url: https://www.rcac.purdue.edu/about/staff/rderue
  amaji:
    name: Amiya Maji
    description: Lead Computational Scientist
    avatar: https://www.rcac.purdue.edu/files/users/amaji/photo.jpg
    slug: https://www.rcac.purdue.edu/about/staff/amaji
    url: https://www.rcac.purdue.edu/about/staff/amaji
  aseethar:
    name: Arun Seetharam
    description: Lead Bioinformatics Scientist
    avatar: https://www.rcac.purdue.edu/files/users/aseethar/photo.jpg
    slug: https://www.rcac.purdue.edu/about/staff/aseethar
    url: https://www.rcac.purdue.edu/about/staff/aseethar
  remender:
    name: Josh Remender
    description: HPC Support Specialist
    avatar: https://www.rcac.purdue.edu/files/staff_thumb.png
    slug: https://www.rcac.purdue.edu/about/staff/remender
    url: https://www.rcac.purdue.edu/about/staff/remender