name: Run Make on modulefiles change

on:
  push:
    branches:
      - auto_app
    paths:
      - 'docs/software_datasets/modulefiles/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/software_datasets/scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make

      - name: Commit and push changes
        run: |
          git config --global user.name "Guangzhen-Jin"
          git config --global user.email "jin456@purdue.edu"
          
          git add ../software/md ../software/app_catalog.md
          git commit -m "Auto-update app catalog and markdown files" || echo "No changes to commit"
          git push